### ISSUE TITLE
Checkbox is not checked when click on the "background area"

### ISSUE THREAD

**Issue by MarceloLuis1997** [bantikyan/icheck-material#3]
Hello,
First of all, thanks for this awesome work you've done!

But.. I am having some problems when click on the "background area" of the checkbox but outside label element, when clicking it the background pulse effect is show but the checkbox are not checking/unchecking. This problem happen even in your [Demo Page](https://bantikyan.github.io/icheck-material/)

I've tried some CSS fixes but with no success, can you please check it?
Thanks!

**Comment by bantikyan** [comment]
Hello @MarceloLuis1997 
Thank you for kind words and support. I really happy you liked.

I have fixed the issue you mentioned and published new version: 1.0.1
Please try new version and inform me if everything works now on you end.

**Comment by MarceloLuis1997** [comment]
Hello @bantikyan ,
It worked! Thank you very much and have a nice week :D
